### ISSUE TITLE
Traceback when parsing AWS tfstate

### ISSUE THREAD

**Issue by siddharthist** [CiscoCloud/terraform.py#31]
After provisioning with [mantl's default aws.tf file](https://github.com/CiscoCloud/mantl/blob/master/terraform/aws/aws.tf), I got the following traceback with terraform.py. I've saved my tfstate as well, but didn't post it due to it's length. 
```
ERROR! The file plugins/inventory/terraform.py is marked as executable, but failed to execute correctly. If this is not supposed to be an executable script, correct this with `chmod -x plugins/inventory/terraform.py`.
ERROR! Inventory script (plugins/inventory/terraform.py) had an execution error: Traceback (most recent call last):
  File "/home/siddharthist/Dropbox/code/asteris/mantl/plugins/inventory/terraform.py", line 545, in <module>
    main()
  File "/home/siddharthist/Dropbox/code/asteris/mantl/plugins/inventory/terraform.py", line 533, in main
    print(json.dumps(output, indent=4 if args.pretty else None))
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 180, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: dict_values([]) is not JSON serializable
 
ERROR! plugins/inventory/terraform.py:16: Error parsing host definition '"""\': No escaped character
```

**Comment by siddharthist** [comment]
Just kidding, Python version issue.

**Comment by LinuxArchitects** [comment]
I got some issue with the terraform.py : 
it works fine for 1 week and the without changing anything i got this issue :

ERROR! Inventory script (terraform.py) had an execution error: Traceback (most recent call last):
  File "/home/heddar/Terraform_aws/terraform.py", line 445, in <module>
    main()
  File "/home/heddar/Terraform_aws/terraform.py", line 434, in main
    output = query_list(hosts)
  File "/home/heddar/Terraform_aws/terraform.py", line 388, in query_list
    for name, attrs, hostgroups in hosts:
  File "/home/heddar/Terraform_aws/terraform.py", line 65, in iterhosts
    for module_name, key, resource in resources:
  File "/home/heddar/Terraform_aws/terraform.py", line 44, in iterresources
    for filename in filenames:
  File "/home/heddar/Terraform_aws/terraform.py", line 37, in tfstates
    for dirpath, _, filenames in os.walk(root):
  File "/usr/lib64/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 294, in walk
    for x in walk(new_path, topdown, onerror, followlinks):
  File "/usr/lib64/python2.7/os.py", line 284, in walk
    if isdir(join(top, name)):
  File "/usr/lib64/python2.7/genericpath.py", line 41, in isdir
    st = os.stat(s)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 98: ordinal not in range(128)

Any idea ?

Python 2.7.5
Ansible 2.2.0
CentOS Linux release 7.2.1511 (Core)

**Comment by LinuxArchitects** [comment]
Sorry it's a problem with my : 

echo $LC_ALL 
export LC_ALL='en_US.utf8'

works very fine now
